version: '3.4'

services:
  recipeservice:
    image: ${DOCKER_REGISTRY-}recipeservice
    environment:
      DBType: mssql
      mssql: "Server=sql-server-db,1433;Database=Recipe;User Id=sa;Password=RecipeHallo!23;TrustServerCertificate=true"
    build:
      context: .
      dockerfile: RecipeService/Dockerfile
    ports:
      - "10080:80"
      - "10443:443" 
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1400:1433"
    environment:
      SA_PASSWORD: "RecipeHallo!23"
      ACCEPT_EULA: "Y"
